# Numpy
Numerical Python - package yang bisa kita gunakan untuk proses angka (mueric) di Python. Digunakan juga oleh banyak package Python lainnya.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# tipe struktur data Numpy Array
- mirip List
- bukan List

CRUD:
1. cara membuat (Create)
2. cara baca (Read)
3. cara update (Update)
4. cara hapus (Delete)

### np.array()

In [6]:
# Cara membuat (Create) numpy array
# 1. dari List

arr = np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [77]:
arr = np.array([[1,2,3],[3,2,1]])
print(arr)
print(type(arr))

[[1 2 3]
 [3 2 1]]
<class 'numpy.ndarray'>


In [7]:
# perhatikan perbedaannya dengan list
list_angka = [1,2,3]
print(list_angka)
print(type(list_angka))

[1, 2, 3]
<class 'list'>


### np.zeros()

In [10]:
# 2. np.zeros, membuat numpy array isinya angka 0 semua
arr0 = np.zeros(10)
print(arr0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [80]:
arr0 = np.zeros((3,2))
print(arr0)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


### np.ones()

In [11]:
# 3. np.ones, membuat numpy array isinya angka 1 semua
arr1 = np.ones(10)
print(arr1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [81]:
arr1 = np.ones((2,3))
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]]


### np.empty()

In [15]:
# 4. np.empty, membuat numpy array isinya kosong/ gk ada isinya
arre = np.empty(11)
print(arre)

[9.37543481e-312 1.77863633e-322 0.00000000e+000 0.00000000e+000
 7.56587583e-307 4.03488629e+175 1.74248590e-076 6.19651880e-091
 4.03397451e+175 1.42404755e-306 5.97819431e-322]


In [84]:
arre = np.empty((3,1))
print(arre)

[[2.00538455e+262]
 [2.34784384e+251]
 [1.21790868e-152]]


### np.arange()

In [19]:
# 5. np.arange, membuat numpy array isinya angka urut
arr_range = np.arange(5, 15, 2)
print(arr_range)

[ 5  7  9 11 13]


In [85]:
arr_range = np.arange(5, 16, 2).reshape((2,3))
print(arr_range)

[[ 5  7  9]
 [11 13 15]]


### np.random.random()
membuat numpy array isinya angka random yang terdistribusi dengan random juga. (distribusi ada banyak jenis, bukan random aja)

In [152]:
arr_random = np.random.random(10)
print(arr_random)

[0.39816056 0.26659469 0.4378166  0.0128114  0.58065058 0.08074721
 0.58689274 0.26965138 0.36992357 0.58321015]


In [153]:
arr_random = np.random.random((2,3))
print(arr_random)

[[0.52936459 0.50592024 0.40754465]
 [0.55090162 0.88492807 0.00577383]]


In [159]:
# mau lempar dadu 10 kali (hasil dadu 1-6)
arr_dadu = (np.random.random(10) * 6 + 1).astype(int)
print(arr_dadu)

[4 6 5 4 2 5 6 3 6 2]


### append, delete, sort

In [22]:
# cara update - append, delete, sort

print(arr_range)

[ 5  7  9 11 13]


In [28]:
# tambah angka baru pakai append
arr_baru = np.append(arr_range, 10)
print(arr_baru)
print(arr_range)

[ 5  7  9 11 13 10]
[ 5  7  9 11 13]


In [35]:
arr_baru = np.append(arr_range, [4,3,7])
print(arr_baru)
print(arr_range)

[ 5  7  9 11 13  4  3  7]
[ 5  7  9 11 13]


In [27]:
# hapus sebuah angka menggunakan index nya pakai delete
arr_baru = np.delete(arr_range, 0)
print(arr_baru)
print(arr_range)

[ 7  9 11 13]
[ 5  7  9 11 13]


In [36]:
# sortir angka yang ada di dalam sebuah numpy array pakai sort
arr_berantakan = np.array([3,7,3,-345,45,3467,0,-76])
arr_baru = np.sort(arr_berantakan)
print(arr_berantakan)
print(arr_baru)

[   3    7    3 -345   45 3467    0  -76]
[-345  -76    0    3    3    7   45 3467]


### shape, size

In [37]:
# cara bacanya sama seperti list, kita bisa gunakan index
# contoh: ambil angka ke-4 (index 3) dari arr_range
print(arr_range[3])

# teknik slicing juga bisa digunakan

11


kita juga bisa lihat property dari sebuah numpy array, bentuknya, ukurannya

In [38]:
print(arr_baru)

[-345  -76    0    3    3    7   45 3467]


In [41]:
print(arr_baru.shape)

(8,)


In [42]:
print(arr_baru.size)

8


In [43]:
print(arr_baru.ndim)

1


ndim menunjukkan numpy array tersebut ada berapa dimensi. makanya namanya numpy.ndarray - nd adalah jumlah dimensi dari sebuah numpy array. n dimension. jumlah dimensi nya bisa 1,2,3,...

In [49]:
# contoh array 2 dimensi
arr9 = np.array([[1,2],[5,6],[8,9]])
print(arr9)
print(arr9.shape)
print(arr9.size)
print(arr9.ndim)

[[1 2]
 [5 6]
 [8 9]]
(3, 2)
6
2


### reshape
mengubah shape sebuah numpy array

In [51]:
print(arr9)

[[1 2]
 [5 6]
 [8 9]]


In [52]:
print(arr9.reshape(2,3))

[[1 2 5]
 [6 8 9]]


In [53]:
print(arr9)

[[1 2]
 [5 6]
 [8 9]]


In [55]:
print(arr9.reshape(6,))

[1 2 5 6 8 9]


In [56]:
print(arr9.reshape(6,1))

[[1]
 [2]
 [5]
 [6]
 [8]
 [9]]


In [57]:
print(arr9.reshape(1,6))

[[1 2 5 6 8 9]]


In [61]:
print(arr9.reshape(2,3,1))

[[[1]
  [2]
  [5]]

 [[6]
  [8]
  [9]]]


### membuat np array 1D menjadi 2D
- np.newaxis
- np.expand_dims

In [63]:
arr = np.array([2,4,6,8,3,5,7,9,12,13,14,15])
print(arr.shape)
print(arr.size)
print(arr.ndim)

(12,)
12
1


In [69]:
arr_baru = arr[np.newaxis]
print(arr_baru)

print(arr_baru.shape)
print(arr_baru.size)
print(arr_baru.ndim)

[[ 2  4  6  8  3  5  7  9 12 13 14 15]]
(1, 12)
12
2


In [67]:
arr_baru = arr[:, np.newaxis]
print(arr_baru)

print(arr_baru.shape)
print(arr_baru.size)
print(arr_baru.ndim)

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [12]
 [13]
 [14]
 [15]]
(12, 1)
12
2


In [71]:
arr_baru = arr.reshape((1,12))
print(arr_baru)

print(arr_baru.shape)
print(arr_baru.size)
print(arr_baru.ndim)

[[ 2  4  6  8  3  5  7  9 12 13 14 15]]
(1, 12)
12
2


In [73]:
arr_baru = np.expand_dims(arr, axis=0)
print(arr_baru)

print(arr_baru.shape)
print(arr_baru.size)
print(arr_baru.ndim)

[[ 2  4  6  8  3  5  7  9 12 13 14 15]]
(1, 12)
12
2


In [74]:
arr_baru = np.expand_dims(arr, axis=1)
print(arr_baru)

print(arr_baru.shape)
print(arr_baru.size)
print(arr_baru.ndim)

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [12]
 [13]
 [14]
 [15]]
(12, 1)
12
2


In [76]:
arr_baru = arr.reshape((3,2,2))
print(arr_baru)

print(arr_baru.shape)
print(arr_baru.size)
print(arr_baru.ndim)

[[[ 2  4]
  [ 6  8]]

 [[ 3  5]
  [ 7  9]]

 [[12 13]
  [14 15]]]
(3, 2, 2)
12
3


In [87]:
# indexing dan slicing
data = np.arange(6)
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[0 1 2 3 4 5]
0
1
[0 1]
[1 2 3 4 5]
[4 5]


In [88]:
# dengan kondisi
print(data[data>3])

[4 5]


In [89]:
print(data[data%2==0])

[0 2 4]


In [91]:
data_genap = data%2==0
data_lebih3 = data>3
print(data[data_genap])

[0 2 4]


In [92]:
print(data[data_genap & data_lebih3])

[4]


In [93]:
print(data[(data%2==0) & (data>3)])

[4]


In [94]:
print(data[data_genap | data_lebih3])

[0 2 4 5]


### membuat array dari array
- slicing (ambil bbrp item dari sebuah array jadi array baru)
- stack (menempel bbrp array jadi satu)
    - secara horizontal (tempelin kiri ke kanan)
    - secara vertical (tempelin atas ke bawah)
- split (memotong satu array jadi bbrp bagian)
    - secara horizontal (bagi nya dipisah dari kiri ke kanan)
    - secara vertical (baginya dipisah dari atas dan bawah)
- copy (membuat copy sebuah array)
    - view (shallow copy, kena pass by reference)
    - copy (deep copy, membuat array baru)

In [95]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [96]:
# slicing
arr1 = arr[3:8]
print(arr1)

[4 5 6 7 8]


In [97]:
# stack
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8],[9,10]])
print(a1)
print(a2)

[[1 2]
 [3 4]]
[[ 5  6]
 [ 7  8]
 [ 9 10]]


In [99]:
# vertical stack, vstack
arr_baru = np.vstack((a1, a2))
print(arr_baru)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [101]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6,7],[8,9,10]])
print(a1)
print(a2)

[[1 2]
 [3 4]]
[[ 5  6  7]
 [ 8  9 10]]


In [102]:
# horizontal stack, hstack
arr_baru = np.hstack((a1, a2))
print(arr_baru)

[[ 1  2  5  6  7]
 [ 3  4  8  9 10]]


In [103]:
arr_baru = np.hstack((a1, a2, a1))
print(arr_baru)

[[ 1  2  5  6  7  1  2]
 [ 3  4  8  9 10  3  4]]


In [104]:
arr_baru = np.hstack((a1, a1))
print(arr_baru)

[[1 2 1 2]
 [3 4 3 4]]


### split
membagi 1 array jadi bbrp bagian

In [108]:
arr_contoh = np.arange(-10,24,3).reshape(3,4)
print(arr_contoh)

[[-10  -7  -4  -1]
 [  2   5   8  11]
 [ 14  17  20  23]]


In [109]:
np.hsplit(arr_contoh,2)

[array([[-10,  -7],
        [  2,   5],
        [ 14,  17]]),
 array([[-4, -1],
        [ 8, 11],
        [20, 23]])]

In [111]:
np.vsplit(arr_contoh,3)

[array([[-10,  -7,  -4,  -1]]),
 array([[ 2,  5,  8, 11]]),
 array([[14, 17, 20, 23]])]

### view, copy

In [112]:
arr_view = arr_contoh.view()
arr_copy = arr_contoh.copy()

In [113]:
print(arr_view)
print(arr_copy)

[[-10  -7  -4  -1]
 [  2   5   8  11]
 [ 14  17  20  23]]
[[-10  -7  -4  -1]
 [  2   5   8  11]
 [ 14  17  20  23]]


In [114]:
arr_contoh[0] = 0
print(arr_contoh)

[[ 0  0  0  0]
 [ 2  5  8 11]
 [14 17 20 23]]


In [115]:
print(arr_view)
print(arr_copy)

[[ 0  0  0  0]
 [ 2  5  8 11]
 [14 17 20 23]]
[[-10  -7  -4  -1]
 [  2   5   8  11]
 [ 14  17  20  23]]


In [116]:
arr_view[0,0] = -10
arr_copy[0,0] = 100

In [117]:
print(arr_contoh)

[[-10   0   0   0]
 [  2   5   8  11]
 [ 14  17  20  23]]


In [118]:
print(arr_view)
print(arr_copy)

[[-10   0   0   0]
 [  2   5   8  11]
 [ 14  17  20  23]]
[[100  -7  -4  -1]
 [  2   5   8  11]
 [ 14  17  20  23]]


# Array operations
tambah, kurang, kali, bagi, akar, pangkat, dll semua bisa di numpy array

In [120]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [121]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [122]:
arr10 = np.ones(10) * 10
print(arr10)

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [123]:
arr + arr10

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [125]:
arr_baru = arr * 2 / 5 - 3
print(arr_baru)

[-3.  -2.6 -2.2 -1.8 -1.4 -1.  -0.6 -0.2  0.2  0.6]


In [126]:
arr_baru = arr_baru.reshape(2,5)
print(arr_baru)

[[-3.  -2.6 -2.2 -1.8 -1.4]
 [-1.  -0.6 -0.2  0.2  0.6]]


In [127]:
# sum
arr_baru.sum()

-12.000000000000002

In [128]:
# sum seluruh baris (baris 1 + baris 2 + ...)
arr_baru.sum(axis=0)

array([-4. , -3.2, -2.4, -1.6, -0.8])

In [129]:
# sum seluruh kolom (kolom 1 + kolom 2 + ...)
arr_baru.sum(axis=1)

array([-11.,  -1.])

In [130]:
arr_baru + 10

array([[ 7. ,  7.4,  7.8,  8.2,  8.6],
       [ 9. ,  9.4,  9.8, 10.2, 10.6]])

In [131]:
arr_baru * -10

array([[30., 26., 22., 18., 14.],
       [10.,  6.,  2., -2., -6.]])

selain sum, bisa juga kita cari:
- max
- min
- mean (rata2)
- product (hasil perkalian)
- std (standard deviation, angka statistik menunjukkan penyebaran)
- lainnya

In [135]:
arr_baru = np.array([[1,2,3],[9,10,11]])
print(arr_baru)

[[ 1  2  3]
 [ 9 10 11]]


In [136]:
# max, min, mean
print(arr_baru.max())
print(arr_baru.min())
print(arr_baru.mean())

11
1
6.0


In [137]:
# bandinginnya per baris
print(arr_baru.max(axis=0))
print(arr_baru.min(axis=0))
print(arr_baru.mean(axis=0))

[ 9 10 11]
[1 2 3]
[5. 6. 7.]


In [138]:
# bandinginnya per kolom
print(arr_baru.max(axis=1))
print(arr_baru.min(axis=1))
print(arr_baru.mean(axis=1))

[ 3 11]
[1 9]
[ 2. 10.]


# Matrices/ Matrix
array 2 dimensi isinya angka semua, tidak ada yang bolong. semua baris punya jumlah kolom yang sama. semua kolom punya jumlah baris yang sama.   

kalau jumlah kolom cuman 1, namanya vector. tapi disini anggap saja itu adalah matrix dengan 1 kolom.

In [139]:
# contoh bikin matrix, numpy array 2d isi angka semua

m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[7,8],[9,10],[11,12]])
print(m1)
print(m2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


### dot product

contoh dot product, untuk secara visual bisa dilihat di web https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [141]:
np.dot(m1,m2)

array([[ 58,  64],
       [139, 154]])

In [142]:
harga = np.array([[3,4,2]])
penjualan = np.array([[13,9,7,15],
                     [8,7,4,6],
                     [6,4,0,3]])
print(harga)
print(penjualan)

[[3 4 2]]
[[13  9  7 15]
 [ 8  7  4  6]
 [ 6  4  0  3]]


In [144]:
print("total penjualan")
perhari = np.dot(harga, penjualan)
print("perhari", perhari)
print("total 4 hari", perhari.sum())

total penjualan
perhari [[83 63 37 75]]
total 4 hari 258


### transposing

In [145]:
# reshape mengubah bentuk sebuah numpy array
print(penjualan)

[[13  9  7 15]
 [ 8  7  4  6]
 [ 6  4  0  3]]


In [147]:
print(penjualan.reshape((4,3)))

[[13  9  7]
 [15  8  7]
 [ 4  6  6]
 [ 4  0  3]]


In [149]:
print(penjualan.transpose())

[[13  8  6]
 [ 9  7  4]
 [ 7  4  0]
 [15  6  3]]


In [151]:
print(penjualan.T)

[[13  8  6]
 [ 9  7  4]
 [ 7  4  0]
 [15  6  3]]


### flatten dan ravel
flatten -> ubah array jadi 1d, deep copy mirip .copy()   
ravel -> ubah array jadi 1d, by reference mirip .view()

In [160]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [161]:
arr_flat = arr_2d.flatten()
arr_ravel= arr_2d.ravel()
print(arr_flat)
print(arr_ravel)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [162]:
arr_ravel[0] = 100
arr_flat[0] = -3

print(arr_ravel)
print(arr_flat)
print(arr_2d)

[100   2   3   4   5   6   7   8   9  10  11  12]
[-3  2  3  4  5  6  7  8  9 10 11 12]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
